CREATE TABLE channel_subscriptions
(
    subscription_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    customer_id     BIGINT                                  NOT NULL,
    channel_id      BIGINT                                  NOT NULL,
    is_subscribed   BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_channel_subscriptions PRIMARY KEY (subscription_id)
);

CREATE TABLE channels
(
    channel_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    channel_name VARCHAR(100)                            NOT NULL,
    channel_type VARCHAR(50)                             NOT NULL,
    description  VARCHAR(500),
    is_active    BOOLEAN                                 NOT NULL,
    owner_id     BIGINT                                  NOT NULL,
    CONSTRAINT pk_channels PRIMARY KEY (channel_id)
);

CREATE TABLE customers
(
    customer_id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    customer_name       VARCHAR(100)                            NOT NULL,
    email               VARCHAR(100)                            NOT NULL,
    phone_number        VARCHAR(20),
    is_active           BOOLEAN                                 NOT NULL,
    is_marketing_agreed BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_customers PRIMARY KEY (customer_id)
);

CREATE TABLE message_histories
(
    history_id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    message_id       BIGINT                                  NOT NULL,
    customer_id      BIGINT                                  NOT NULL,
    publish_status   VARCHAR(20)                             NOT NULL,
    published_at     TIMESTAMP WITHOUT TIME ZONE,
    error_message    VARCHAR(1000),
    retry_count      INTEGER                                 NOT NULL,
    schedule_rule_id BIGINT,
    CONSTRAINT pk_message_histories PRIMARY KEY (history_id)
);

CREATE TABLE messages
(
    message_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    channel_id   BIGINT                                  NOT NULL,
    title        VARCHAR(200)                            NOT NULL,
    content      TEXT                                    NOT NULL,
    message_type VARCHAR(20)                             NOT NULL,
    status       VARCHAR(20)                             NOT NULL,
    created_by   BIGINT                                  NOT NULL,
    CONSTRAINT pk_messages PRIMARY KEY (message_id)
);

CREATE TABLE schedule_rules
(
    schedule_id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    message_id          BIGINT                                  NOT NULL,
    schedule_type       VARCHAR(20)                             NOT NULL,
    cron_expression     VARCHAR(100),
    execution_time      TIMESTAMP WITHOUT TIME ZONE,
    next_execution_time TIMESTAMP WITHOUT TIME ZONE,
    last_execution_time TIMESTAMP WITHOUT TIME ZONE,
    is_active           BOOLEAN                                 NOT NULL,
    job_name            VARCHAR(200),
    job_group           VARCHAR(200),
    execution_count     INTEGER                                 NOT NULL,
    max_execution_count INTEGER,
    CONSTRAINT pk_schedule_rules PRIMARY KEY (schedule_id)
);

ALTER TABLE customers
    ADD CONSTRAINT uc_customers_email UNIQUE (email);

ALTER TABLE schedule_rules
    ADD CONSTRAINT uc_schedule_rules_job_name UNIQUE (job_name);

ALTER TABLE channel_subscriptions
    ADD CONSTRAINT uk_customer_channel UNIQUE (customer_id, channel_id);

CREATE INDEX idx_email ON customers (email);

CREATE INDEX idx_is_active ON schedule_rules (is_active);

CREATE INDEX idx_next_execution_time ON schedule_rules (next_execution_time);

CREATE INDEX idx_phone_number ON customers (phone_number);

CREATE INDEX idx_publish_status ON message_histories (publish_status);

CREATE INDEX idx_published_at ON message_histories (published_at);

CREATE INDEX idx_status ON messages (status);

ALTER TABLE message_histories
    ADD CONSTRAINT FK_HISTORY_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customers (customer_id);

CREATE INDEX idx_customer_id ON channel_subscriptions (customer_id);

ALTER TABLE message_histories
    ADD CONSTRAINT FK_HISTORY_MESSAGE FOREIGN KEY (message_id) REFERENCES messages (message_id);

CREATE INDEX idx_message_id ON schedule_rules (message_id);

ALTER TABLE messages
    ADD CONSTRAINT FK_MESSAGE_CHANNEL FOREIGN KEY (channel_id) REFERENCES channels (channel_id);

CREATE INDEX idx_channel_id ON channel_subscriptions (channel_id);

ALTER TABLE schedule_rules
    ADD CONSTRAINT FK_SCHEDULE_MESSAGE FOREIGN KEY (message_id) REFERENCES messages (message_id);

CREATE INDEX idx_message_id ON schedule_rules (message_id);

ALTER TABLE channel_subscriptions
    ADD CONSTRAINT FK_SUBSCRIPTION_CHANNEL FOREIGN KEY (channel_id) REFERENCES channels (channel_id);

CREATE INDEX idx_channel_id ON channel_subscriptions (channel_id);

ALTER TABLE channel_subscriptions
    ADD CONSTRAINT FK_SUBSCRIPTION_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customers (customer_id);

CREATE INDEX idx_customer_id ON channel_subscriptions (customer_id);