# WebSocket Server 전용 설정
server:
  port: 20002

spring:
  application:
    name: chat-websocket-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

# WebSocket 설정
websocket:
  allowed-origins:
    - http://localhost:3000
    - http://localhost:8080
  endpoint: /ws
  topic-prefix: /topic
  app-prefix: /app
