spring.application.name=eureka-server
server.port=8761

# ?? ???? (?? ? -Dspring.profiles.active=prod ?? override ??)
spring.profiles.active=dev

# Eureka Server - ??? ???? ??
eureka.instance.hostname=localhost
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka/
eureka.server.enable-self-preservation=false
eureka.server.eviction-interval-timer-in-ms=5000
eureka.server.response-cache-update-interval-ms=5000

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# Logging
logging.level.com.netflix.eureka=INFO
logging.level.com.netflix.discovery=INFO
logging.config=classpath:logback-spring.xml
