# ===================================================================
# Prod Profile - eureka-server
# ===================================================================
eureka.instance.hostname=${EUREKA_HOSTNAME:eureka-server}
eureka.server.enable-self-preservation=true
eureka.server.eviction-interval-timer-in-ms=60000
eureka.server.response-cache-update-interval-ms=30000

logging.level.com.netflix.eureka=WARN
logging.level.com.netflix.discovery=WARN
