# ===================================================================
# Dev Profile - eureka-server
# ===================================================================
eureka.instance.hostname=localhost
eureka.server.enable-self-preservation=false

logging.level.com.netflix.eureka=DEBUG
logging.level.com.netflix.discovery=DEBUG
