spring.application.name=config-server
server.port=8888

# Native Profile (?? ?? ??? ??) + ?? ???? dev
# ?? ? -Dspring.profiles.active=prod ?? override ??
spring.profiles.active=native,dev
spring.cloud.config.server.native.search-locations=classpath:/config-repo

# Actuator
management.endpoints.web.exposure.include=health,info,refresh
management.endpoint.health.show-details=always

# Logback
logging.config=classpath:logback-spring.xml
