# ===================================================================
# Dev Profile - config-server
# ===================================================================
logging.level.org.springframework.cloud.config=DEBUG
