# ===================================================================
# Prod Profile - config-server
# Git ?? Config Repository ?? ? ?? ?? ??
# ===================================================================
# spring.profiles.active=git
# spring.cloud.config.server.git.uri=${CONFIG_GIT_URI}
# spring.cloud.config.server.git.default-label=main

logging.level.org.springframework.cloud.config=WARN
