# ===================================================================
# Prod Profile - chat-server
# ===================================================================

# DataSource
spring.datasource.source.url=${DB_SOURCE_URL}
spring.datasource.source.username=${DB_USERNAME}
spring.datasource.source.password=${DB_PASSWORD}
spring.datasource.replica.url=${DB_REPLICA_URL}
spring.datasource.replica.username=${DB_USERNAME}
spring.datasource.replica.password=${DB_PASSWORD}

# JPA
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=validate

# Kafka
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}

# Redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD}

# Micrometer Tracing
management.tracing.sampling.probability=0.1

# Logging
logging.level.root=WARN
logging.level.com.example.chat=INFO
logging.level.org.springframework.security=WARN
logging.level.org.hibernate.SQL=WARN
